### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by rayking12** [iam-Akshat/portfolio#2]
- Nice project, so many improvements from the last time,
-  you should work on your phone version there are parts where the text is too much big
-  and it seems like your dropdown menu is not working properly, it is displaying a strange shape when you open it, 
-  I think you should leave the images from the projects without a background it looks better to me
- The smaller screens doesn't have 100% max- width, they scroll to the left and right

**Comment by iam-Akshat** [comment]
Done
